version: "3"

volumes:
  mongodb_volume:
  tileserver_volume:

services:
  fronted_service:
    build: frontend/
    restart: always
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - SOCKET_IO_PORT
  db_server_service:
    build: server/
    restart: always
    ports:
    - 8082:8082
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - PORT=8082
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=admin
  socket_server_service:
    build: socket-server/
    restart: always
    ports:
    - 8083:8083
    devices:
      - '/dev:/dev'
    privileged: true
    environment:
      - PORT=8083
      - MODEM_PORT=/dev/ttyUSB2
      - MODEM_BAUDRATE=115200
      - MODEM_MOCK_MODE=0
  vector-tileserver:
    image: klokantech/tileserver-gl-light
    ports:
    - "8080:80"
    volumes:
    - tileserver_volume:/data/tileserver
    restart: always
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_volume:/data/db
